scootdev/scoot

clusterMembership/dynamicCluster.go, clusterMembership/staticCluster.go
Updating Dynamic Cluster to store pre-calculated members slice for faster Members() response
Dynamic Cluster remove internal map, no longer needed for fast lookup since sendMessage was removed from Interface
=> Updating Dynamic Cluster & Static Cluster to be Reference Types,

.travis.yml, Makefile
Adding dependencies command to make file.  Using this command to install all dependencies needed for TravisCI build.
The goal is to :
- make it it easy to setup dev environment
- make it easy to sync dependencies when new ones are added
- ensure our build process & dev environment are similar
=> Add Build Dependencies to MakeFile

saga/inMemorySagaLog.go, saga/saga.go, saga/sagaRecovery.go, saga/sagaRecovery_test.go, saga/saga_test.go, saga/sagalog.go, saga/sagalog_mock.go, sched/demo/main.go
Saga Recovery will happen at Startup.  Once a Scheduler starts up it should read, it's saga log, and then reschedule non completed work.  Startup returns a list of SagaIds, RecoverSagaState should then be called per SagaId.  These methods are separate to allow the caller to determine how to handle failures (how many times to retry etc...) also to handle the rate at which the SagaLog is polled, and how quickly tasks are rescheduled.  These decisions are specific to an implementation and therefore should not be abstracted from the user by the Saga package.  
This code review also contains Saga Recovery Logic, which reads Sagas from the SagaLog, replays messages and verifies state is correct, and checks if its safe to proceed otherwise aborts the Saga.  
The demo has been updated to poll the …
=> Saga Recovery

saga/sagaState.go, saga/sagaState_prop_test.go, saga/sagaState_test.go, saga/sagalog.go
Callers need to be able to distinguish between error types, so they know if its transient error i.e. log writes temporarily unavailable or illegal state update.  Test cases updated to check for specific error
Also practicing what I preach In [Simple Test Cases Can Prevent Most Critical Failures](https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-yuan.pdf) one of the big discoveries that aborting on overly generic errors / poor error handling resulted in many catastrophic failures in distributed systems.
=> adding specific errors to saga log

saga/sagaGenerators.go, saga/sagaState.go, saga/sagaState_prop_test.go
Adding  a pretty print for SagaState useful in property based testing and future debugging.  
Removing pointer fun in property based testing that was necessary because we didn't have a pretty print for SagaState
Example of Pretty Print: 
SagaId: 26x1b7fwo85vabt9k, SagaAborted: false, SagaCompleted:
false, Tasks: [ p2ns3hmpz717zc: Started|Completed, cnexxoah1h5ufdi:
Started, c1y0wvdmzqw86vrul: Started|Completed, 2qi7vv9sjwgjj: Started,
qo8q79d6l3z4x: Started|Completed, 9wfhbdeq: Started, mtle3rv2f4mgy3:
Started, 2ttmhtwz3zn9o3p: Started, day4syhcut4hm9l1fm1g: Started,
od0px1zafg0: Started, 43qb5ivpj0f3wpd5l5: Started|Completed,
8p3rftaj30qvnk6h: Started, 0l5qbxzdssf3j: Started, npole3cq5j11ffxuwcg:
Started, i1ike18d41ihdt: Started, tk6o6m: Started, ggyrpdblvbhqd1usw:
Started|Completed, …
=> sagaState ToString function

binaries/daemon/main.go, binaries/workerserver/main.go, runner/execer/execer.go, runner/execer/fake/sim.go, runner/local/simple.go, runner/local/simple_test.go, runner/runner.go, runner/status.go, snapshots/fake/fake_filer.go, snapshots/filer.go
Filer offers high-level interaction with Snapshots. Checkout a Snapshot into the
local filesystem, or Ingest the local filesystem into a Snapshot. (For now we
only offer Checkout).
Use this abstraction in Runner and extend the Execer interface to take a Dir.
This means that Runner knows about Scoot (it deals with Snapshots), but Execer
doesn't.
Restructure the run code in Runner. It's now more clear who's responsible for
modifying what. This was necessary because checking out may take some time,
and we want to let the user cancel the job while it's happening. This has the
slight negative that the Worker returning to the client no longer means the
command is running. It would be nice if we could reinstate this. In the common
case, we have to wait for a quick checkout, but we may have to …
=> snapshots: Checkouter; the first piece of Filer

Makefile, tests/swarmtest/swarmtest_test.go
Turns out you can do "not this tag" semantics you just need to escape the bang!
=> Makefile BuildTag Update: Escape the Bang!

cloud/cluster/cluster.go, cloud/cluster/cluster_test.go, cloud/cluster/fetch_cron.go, cloud/cluster/fetch_cron_test.go, cloud/cluster/local/config.go, cloud/cluster/local/fetcher.go, cloud/cluster/subscription.go, sched/config/defaults.go
I found that I couldn't easily change the duration on the fetch cron because it was pulled in.
I made a few changes to make things more injected instead of constructed at the same time.
Got rid of all functions Subcribe(), which don't make sense outside of the context of a Cluster.
=> cloud/cluster: simplify construction

binaries/daemon/main.go, binaries/workerserver/main.go, runner/execer/execer.go, runner/execer/fake/sim.go, runner/execer/os/easy_test.go, runner/execer/os/os_execer.go, runner/local/output.go, runner/local/simple.go, runner/local/simple_test.go, runner/output.go
Runner uses Saver to save stdout and stderr.
localSaver saves to a local file (in tempdir)
Future impls of Saver could upload to hdfs, s3, etc.
Saver is temporary until we have the ability to save all output (stdout/stderr but also created files) into a new Snapshot.
=> runner: Saver lets clients Save output 

scootapi/client/smoke_test_cmd.go
scootapi's smoke_test would sometimes deadlock. We don't actually need to update it concurrently, so just do it simply on one goroutine
=> scootapi/client: update smoketest on one goroutine

workerapi/client/cli.go, workerapi/client/client.go, workerapi/client/commands.go
Create a small interface cmd. Each cmd is responsible for:
*) holding its data (the struct fields)
*) registerFlags: registers flags (which will populate its struct fields)
*) run: does its job
=> workerapi/client: refactor how we create commands

binaries/daemon/main.go, binaries/workerserver/main.go, runner/execer/execers/intercept.go, runner/execer/execers/intercept_test.go, runner/execer/execers/sim.go, runner/execer/execers/sim_test.go, runner/local/simple_test.go, tests/testhelpers/generators.go
InterceptorExecer looks at its first argument and, if it matches a condition, passes it to an execer (the interceptor) or if not passes it to the default.
This lets us include both sim and os execer in the same binary and then pick which to use at command runtime based n the command-line. So we can still simulate commands, or run them via the OS.
=> runner/execer/fake: interceptor execer picks execer based on argv

sched/generators.go, sched/scheduler/scheduler.go, sched/scheduler/scheduler_mock.go, sched/scheduler/stateful_scheduler.go, sched/scheduler/stateful_scheduler_test.go, scootapi/server/run_job.go, scootapi/server/run_job_test.go
Currently the JobId is generated in ScootAPI.  Logically it makes more sense for the scheduler to own this and return an Id if the job was successfully scheduled.  No functionality changes occur in this code review
No functionality Changed
* Updated Scheduler Interface to take a JobDefinition and return a JobId 
* Updated Generators 
* Moved JobId generation from scootapi to statefulscheduler
=> [scheduler] refactor - move jobId generation to scheduler

.gitignore, .travis.yml, os/temp/temp_dir.go, snapshot/git/gitfiler/checkouter.go, snapshot/git/gitfiler/checkouter_test.go, snapshot/git/repo/repo.go
Using git clone reference lets us have many clones without taking lots of disk space. This will let us do work in the background (eventually; not yet implemented).
=> snapshot/git: create checkouts with git clone --reference

binaries/daemon/main.go, binaries/workerserver/main.go, os/temp/temp_dir.go, runner/local/output.go, runner/local/simple.go, runner/local/simple_test.go, snapshot/git/gitfiler/checkouter.go, snapshot/git/gitfiler/checkouter_test.go, snapshot/git/gitfiler/cloner.go, snapshot/git/gitfiler/doc.go, snapshot/git/gitfiler/pool.go, snapshot/git/gitfiler/setup.go, snapshot/git/repo/repo.go
Break down gitfiler a bit more. 
Checkouter: Checks out a Snapshot ID by running git checkout
RepoGetter: interface to get a Repo
RefCloner: RepoGetter that gets a repo by running git clone --reference
RepoPool: holds Repos and manages concurrent access. Can get new ones if given a RepoGetter
By building these blocks together in different ways, a client can choose whether to always make a new clone (setup.go.NewRefRepoCloningCheckouter) or always use the same Repo (setup.go.NewSingleRepoCheckouter)
Document in gitfiler/doc.go
log in local.simpleRunner to make it easier to follow in workerServer's stderr
Use TempDir in more places to be more consistent about where we store output.
=> snapshot/git/gitfiler: refactor Checkouter

binaries/scheduler/main.go, scootapi/server/setup.go
Binary Flags should not be in apiserver setup code.  These are actually different per binary.  In Source they are based on http and thrift endpoints, and are actually different (my mistake!)
Refactored code that uses flags out of common server setup code and into main.
=> [Scheduler] flags should not be common

binaries/setup-cloud-scoot/main.go, tests/swarmtest/swarmtest.go
Before this change, if a user of this library overloaded Run, we'd always run, not wait.
=> swarmtest: look at wait in Main, not InitOptions

Makefile, sched/scheduler/stateful_scheduler.go, sched/scheduler/stateful_scheduler_test.go
@ryancouto noticed that all tasks were getting scheduled to one worker.  This is because of a for loop concurrency bug.  All nodes got scheduled once, but only one ever got marked as unscheduled.  Fixed the bug, and added a test case to ensure we are evenly distributing tasks across our nodes.
Also switched out log for fmt in stateful_scheduler.go
=> [scheduler] fixing uneven distribution of tasks bug

binaries/scheduler/config/config.go, runner/local/simple.go, runner/local/simple_test.go, runner/status.go
- runner releases checkout resource if run cancelled before checkout is complete
- some cleanup wrt multiple uses of "run" in simple.go
- runner final updateStatus calls clearer, not relying on inner function logic
- test package rename per convention
- set stdout/stderr refs in run status sooner, and preserve them if status updated later
Main issue was IDd via code inspection - thinking about how to implement positive/negative tests to verify checkout.Release() calls
=> runner/local ensure checkout release in runner, cleanup

ice/eval.go, ice/eval_test.go
Errors thrown called within Ice MagicBag exec/evals were printing the offending function as a memory address. This prints the function name. Func name resolution wizardry is per http://stackoverflow.com/questions/7052693/how-to-get-the-name-of-a-function-in-go
=> ice/eval - print provider function name correctly when error is thrown

binaries/workerserver/main.go, workerapi/server/setup.go
Updating the default magic bag to include all defaults, main.go should override the ones it want's to use.  
tested via 
go run ./binaries/setup-cloud-scoot/main.go --strategy local.local
go run ./binaries/scootapi/main.go run_smoke_test
=> [workerserver] magic bag updates

workerapi/server/server.go
This is part of the workerserver config refactor (final PR!) 
Now that this method is no longer used in twitter source, we can safely remove it.  Any future binaries should use the code in setup.go
=> [worker server] removing unused method

binaries/scheduler/config/config.go, binaries/scheduler/config/local.local, binaries/scheduler/main.go, config/scootconfig/modules.go, sched/worker/workers/polling.go, sched/worker/workers/polling_test.go
We are running into problems testing targets in source.  Some go off and never complete.  Adding a configurable timeout via the scheduler on tasks.  Once the timeout is reached the scheduler will mark the task as completed, but it will be marked with Status TIMEDOUT.  
* I also made the Polling Period Configurable while I was in that code.  
* fixed default config name in scheduler main.go since that never got updated with @dbentley changes.
* Renamed MakeRPCWorkerFactory to Create() to be consistent with the rest of the config objects
=> [Scheduler] Adding timeout to tasks

daemon/integration/python/integration.py
Modify sys.path so that the test python script can be invoked from any dir, not just the dir where the script lives.
=> Modify sys.path

saga/saga.go, saga/saga_test.go, saga/sagalog.go, saga/sagalogs/file_saga_log.go, saga/sagalogs/file_saga_log_test.go
Create a file based saga log.  This is to enable testing of SagaRecovery, currently InMemorySaga does not survive beyond process restart.  File Based SagaLog will be durable beyond process restart , but not beyond machine failure. 
Added CorruptedSagaLog as a Fatal Error.  This should not happen in production unless we did something really wrong (made a breaking change), but allows us to easily detect via test cases if our parsing and reading of the SagaLog files works correctly.
=> [Sagas] Caitie/file saga log

scootapi/client/cli.go, scootapi/client/smoke_test_cmd.go
Currently SmokeTest fails as soon as the scheduler dies.  Any call to ScootAPI that fails results in the test failing.  However, we want to test scheduler restarts, which means some calls may fail.
This update allows failures to the scheduler to be retried.  Currently by reusing the ScootApiClient associated with the Dialer, a broken pipe will be broken forever so Dial() needs to create a new scootClient connection on every call
=> retry smoke test & dial update

binaries/scheduler/config/config.go, scootapi/client/cli.go
This was broken - the check of the addr flag was being done before cobra had parsed the flags, which meant it always fell through to use ~/.cloudscootaddr
=> scootapi/client - fix client addr flag parsing

scootapi/client/get_status_cmd.go
scootapi exits 0 when it can't connect.
=> scootapi/client - Add default error case to client get_status cmd

snapshot/git/gitdb/bundlestore.go, snapshot/git/gitdb/create.go, snapshot/git/gitdb/db_test.go
In bundlestore.go, if the we're asked to ingest a comit that's on the branch
in the stream, then return a snap from the stream (instead of trying to
upload)
create.go: when we were adding env variables to our run of git, we were
actually not using any of the existing environment; oops.
=> snapshot/git: a few fixes

runner/runners/polling.go, runner/runners/polling_test.go
Tasks have been timing out without a timeout being set. This is because the timeout default value is 0. A timeout of 0 should be read as absence of a timeout, not as a 0 second timeout. If there is no timeout, then we should poll indefinitely.
=> Poll indefinitely if there is no timeout

sched/scheduler/task_scheduler_test.go
This just fixes a `go vet` error in newer versions of go.
=> Trivial fix go vet failure in 1.7.5

runner/execer/os/easy_test.go, runner/execer/os/os_execer.go
- Kill lingering processes with same pgid as monitored command on both success and fail
- Monitor mem usage using process group id instead of parent process id. Gives us a more accurate measure of worker memory usage.
- Structured logging to make verbose ps calls easier to parse
=> runner/execer/os: Memory usage and cleanup of processes

binaries/daemon/main.go, common/stats/stats_names.go, common/stats/verify_stats.go, daemon/server/handler_test.go, runner/runners/invoke.go, runner/runners/polling_test.go, runner/runners/queue.go, runner/runners/queue_test.go, runner/runners/single_test.go, sched/scheduler/cluster_state_test.go, sched/scheduler/stateful_scheduler_test.go, sched/scheduler/task_runner_test.go, sched/worker/workers/makers.go, scootapi/server/server_test.go
added metrics to track download/upload latency and counts from the worker - updated worker creation functions to allow passing in the stats collector.
updated the tests to use the constants instead of hard-coded names (forgot to make these changes in the last PR)
=> Jbruno/dx2186 new metrics - worker download/upload

.gitignore, .travis.yml, Makefile, binaries/scoot-snapshot-db/main.go, common/stats/stats_names.go, runner/runners/queue.go, runner/runners/queue_test.go, snapshot/README.md, snapshot/db.go, snapshot/filer.go, snapshot/git/gitdb/db.go, snapshot/git/gitdb/db_test.go, snapshot/git/gitdb/setup.go, snapshot/git/gitdb/stream.go, snapshot/git/gitfiler/checkouter.go, snapshot/git/gitfiler/cloner.go, snapshot/git/gitfiler/doc.go, snapshot/git/gitfiler/pool.go, snapshot/git/gitfiler/setup.go, snapshot/snapshots/fake_filer.go, snapshot/snapshots/fake_updater.go
This adds a mechanism for updating underlying repos.  Updates are synchronized between task runs, which are handled by the Controller.  The QueueController is extended to manage updates between runs.
Controllers are exposed to repos via Filers, so an Updater interface has been added to Filer, and wired down through gitdb as RepoUpdater (paired with existing RepoIniter).
In-practice implementation for closed source is added in https://phabricator.twitter.biz/D57159 (for now, golang impl only)
=> Add support for periodic repo updates

common/stats/stats.go, runner/runners/queue.go, runner/runners/queue_test.go, snapshot/git/gitdb/checkout.go, snapshot/git/gitdb/create.go, snapshot/git/repo/repo.go, workerapi/server/server.go, workerapi/server/server_test.go
This fixes https://jira.twitter.biz/browse/DX-2266, which is a straightforward panic bug, and provides a mitigation for https://jira.twitter.biz/browse/DX-2282, which is a more complicated issue - see ticket for details.  The root cause of that issue is hanging git processes which this addresses to a degree.
=> Fix worker panic and add timeout for git commands

runner/runners/queue.go
Looks straightforward from the log in https://jira.twitter.biz/browse/DX-2297 that svcStatus.Error is nil and was getting dereferenced, although I did not reproduce this.
=> runner/queue - don't dederef nil svcstatus error on startup

runner/runners/invoke.go, sched/scheduler/task_runner.go, sched/scheduler/task_runner_test.go
This fixes the issue where scheduler would exit the run step with in error (namely BADREQUEST) and then continue to send jobs to the same worker which was stuck running the previous command. This isn't comprehensive but Abort() is the only mechanism we currently have to clean up a worker.
=> Defensively abort worker task if it didn't return COMPLETE.

runner/runners/invoke.go, runner/runners/single_test.go, runner/status_rw.go, sched/scheduler/task_runner.go, scootapi/scoot.thrift, workerapi/worker.thrift
The semantics of FAILED and BADREQUEST weren't working well in the scheduler code where we need to mark nodes as flaky depending on what went wrong. FAILED should mean that we had an internal error and BADREQUEST should mean that the user did something wrong.
=> Treat most worker task failures as a reason to mark the associated node flaky.

snapshot/git/repo/repo.go
If cmd.Env is empty, it uses the current process's environment. If len(extraEnv) > 0, then we have to append both the current process's env and extraEnv to cmd.Env
=> Use os.Environ() in addition to extra env vars

runner/execer/os/easy_test.go, runner/runners/invoke.go, runner/runners/polling.go, runner/runners/service_test.go, runner/runners/single_test.go, runner/status.go, sched/generators.go, sched/scheduler/cluster_state.go, sched/scheduler/cluster_state_test.go, sched/scheduler/job_state.go, sched/scheduler/job_state_test.go, sched/scheduler/stateful_scheduler.go, sched/scheduler/stateful_scheduler_property_test.go, sched/scheduler/stateful_scheduler_test.go, sched/scheduler/task_runner.go, sched/scheduler/task_runner_test.go, sched/scheduler/task_scheduler_test.go, scootapi/locate.go, scootapi/scoot.thrift, workerapi/server/server.go, workerapi/worker.thrift
Scheduling tasks by historical run duration is a good-enough optimization until we have clients that can do efficient DAG-based scheduling.
Also fixes mishandling of BADREQUEST after a run request from scheduler -> worker.
=> Schedule long-running tasks first, and fix BADREQUEST handling

config/scootconfig/scheduler_config_modules.go, sched/scheduler/doc.go, sched/scheduler/stateful_scheduler.go, sched/scheduler/stateful_scheduler_test.go, sched/scheduler/task_scheduler.go, sched/scheduler/task_scheduler_test.go
Increase min number of nodes for higher priority jobs.
Allow new related jobs to jump the queue.
Clearer scheduler config defaults.
=> Increase min number of nodes for higher priority jobs.

runner/runners/queue.go, runner/runners/status_manager.go
This is a "feeler" diff for an adjustment to worker logs. The motivations are:
1. make more useful information about tasks available via loglens by promoting them to 'info' level.
2. Get rid of noise in worker by switching over to info level (this will be a closed-source diff).
By promoting these logs to info, the main thing we would ditch from debug level on the worker are the ps output messages from os/os_execer.go's logs, that make it very hard to follow the worker log.
On a worker that's been up ~4 days, the logs promoted here amounted to 500 or so per day average, which I don't think will be an issue for log lens.
Note: if we do this, planning on leaving devel & staging at debug level.
=> scoot/runners - make StatusManager and Queue messages Info

sched/scheduler/job_state.go, sched/scheduler/stateful_scheduler.go, sched/scheduler/task_scheduler.go
We were seeing a panic in task_scheduler kill logic. This disables untested priorities >1 but keeps the job insertion order logic, albeit in a hacky way that should eventually be replaced by a protocol change.
=> Disabled priority>1 since it's not tested.
