scootdev/scoot

Readme.md
CodeCov Badge includes TravisCI Build Status and Code Coverage Badge
=> Add CodeCov Badge to Readme

sched/clusterimplementations/localCluster.go, sched/clustermembership/dynamicCluster_test.go, sched/clustermembership/node.go, sched/clustermembership/staticCluster_test.go, sched/clustermembership/testNode.go, sched/demo/main.go, sched/distributor/distributor.go, sched/distributor/randomDistributor.go, sched/distributor/roundRobinDistributor.go
updating the projects import style to 
import ( 
"fmt"
"errors"
etc..
)
=> updating import style

saga/sagaState.go
Since we are copying SagaState on every state transition, compressing state to BitFlags instead of individual maps.
=> Compressing sagastate

binaries/minfs/main.go, fs/minfuse/fs.go, fs/minfuse/runfs.go, fs/perf/utils.go, fs/perf/utils_test.go, snapshots/file_backed.go
Converted binary/minfs/main.go to a small wrapper that calls common functions in fs/minfuse. Renamed utils->perf.
=> Converted binary/minfs/main.go to a small wrapper.

binaries/scootapi/main.go, scootapi/client/cli.go, scootapi/client/run_job_cmd.go, scootapi/server/serve.go
=> scootapi: allow addr as a flag

sched/clusterimplementations/localCluster.go, sched/clustermembership/node.go, sched/clustermembership/testNode.go, sched/definitions.go, sched/demo/main.go, sched/distributor/distributor.go, sched/distributor/randomDistributor.go, sched/distributor/roundRobinDistributor.go, sched/main.go, sched/queue/memory/simple.go, sched/queue/memory/simple_test.go, sched/queue/queue.go
Move messages into sched package.
Change some capitalization/names in messages
=> sched: create queue abstraction and simple implementation

binaries/localserver/main.go, local/client/cli/cli_test.go, local/client/conn/conn.go, local/protocol/translate.go, runner/README, runner/execer/execer.go, runner/execer/fake/sim.go, runner/execer/fake/sim_test.go, runner/fake/fake.go, runner/local/simple.go, runner/local/simple_test.go, runner/runner.go, runner/status.go
Still way too early for actual review, but shows direction.
=> runner: make a simple runner, introduce execer interface

binaries/scheduler/main.go, binaries/schedulerDemo/main.go, saga/inMemorySagaLog.go, saga/saga.go, saga/sagaCoordinator.go, saga/sagaCoordinator_test.go, saga/sagaRecovery.go, saga/sagaRecovery_test.go, saga/saga_test.go, saga/sagalog.go, sched/scheduler/jobRunner.go, sched/scheduler/scheduler.go
Refactor Saga into SagaCoordinator and Saga.  
Saga controls access to a single SagaState object.  It provides the same API but allows for concurrent updates, i.e. when two tasks start or finish at the same time.  This class provides Read Your Write Consistency.  Once a write successfully completes and returns calling saga.GetState() will reflect the updates just made by the write.
SagaCoordinator class contains basic functions for creating, recovering Sagas that may be in progress.  This also disambiguates a single Saga from general functions on the log.   
Updates Scheduler code to use the new thread-safe saga instead of requiring all consumers of sagas to implement their own thread safe guarantees.
=> Refactor Saga to allow for thread safe updates

common/stats/stats_test.go
I was conflating receiving a message with actually processing it.
=> Deleted ensureChannelSend()

binaries/schedulerDemo/main.go, saga/sagaCoordinator.go, saga/sagaRecovery.go, saga/sagaRecovery_test.go, sched/definitions.go, sched/scheduler/jobStatus.go, sched/scheduler/jobStatus_test.go, sched/scheduler/scheduler_test.go
Adding the Ability to Query Job Status.  Right now this is just code in the scheduler.  Will build the server API on top once this all looks good.
* Added Code to convert SagaState to JobStatus
* Added Non Recovery Status Query To SagaCoordinator.  Removed Rollback RecoveryType from recoverState method not being used.  
* Updated Demo to Check that all Scheduled Jobs have completed before exiting
=> Adding Job Status

binaries/daemon/main.go, binaries/scootcl/main.go, daemon/client/cli/cli.go, daemon/client/cli/cli_test.go, daemon/integration/integration_test.go, daemon/integration/utils.go, daemon/protocol/locate.go, daemon/server/listen.go, daemon/server/listen_test.go, daemon/server/server.go
I accidentally submitted my change to the daemon without the comment about making the directory, so I decided to fix the code to do the todo. And while I was there, it was easy to make it handle this case, as well.
=> daemon: improve server start-up to reclaim old socket

binaries/scheduler/main.go, binaries/workercl/main.go, daemon/client/cli/run_cmd.go, daemon/server/server.go, runner/runner.go, sched/definitions.go, sched/generators.go, sched/queue/memory/simple_test.go, sched/scheduler/jobRunner.go, sched/scheduler/scheduler.go, sched/scheduler/scheduler_test.go, sched/scheduler/workGenerator.go, sched/worker/fake/fake.go, sched/worker/rpc/thriftWorker.go, sched/worker/worker.go, scootapi/client/smoke_test_cmd.go, scootapi/server/serve.go, scootapi/testhelpers/generators.go, workerapi/api.go, workerapi/api_test.go, workerapi/client/cli.go, workerapi/client/client.go, workerapi/client/commands.go, workerapi/worker.thrift
Not quite done but ready for comments.
=> First pass at hooking up scheduler and workerserver.

binaries/workerserver/main.go, runner/execer/fake/sim.go, runner/execer/fake/sim_test.go, scootapi/testhelpers/generators.go
Change sim to take a sleep task
=> smoke_test: change generator to produce <=10 sim'able tasks

scripts/common/smoketest.go, scripts/common/swarmtest.go, scripts/smoketest/smoketest.go, scripts/swarmtest/swarmtest.go
=> Moved most of the smoketest script into a common lib.

saga/inMemorySagaLog.go, scootapi/server/serve.go, scootapi/server/translate_prop_test.go
This makes our tests faster and quieter (so they're easier to run and debug)
=> saga,scootapi/server: remove logging, reduce size

MAINTAINERS
This way they can LGTM pull requests
=> Adding Jeanette & Ryan to maintainers

scootapi/client/targets.go
=> scootapi/client: Delete targets

snapshot/filer.go, snapshot/snapshots/fake_checkouter.go, snapshot/snapshots/fake_filer.go, snapshot/snapshots/fake_filer_test.go
Standalone change, no twitter source updates required.
=> Added snapshot ingestion and created a tmp filer that combines ingest/checkout

.gitignore
=> add *.pyc to .gitignore file

scootapi/client/cli.go, scootapi/setup/setup.go
scootapi/setup: improve error message
=> scootapi/cli: read addr from ~/.cloudscootaddr if unset

scootapi/client/cli.go, scootapi/client/smoke_test_cmd.go
This reverts commit e1edb65a31814dda8c30e0ea172fa0647f0aa433.
There's a bug in this, reverting from master until I figure it out
=> Revert "retry smoke test & dial update (#188)"

binaries/scoot-snapshot-db/main.go, snapshot/cli/cli.go
scoot-snapshot-db create ingest_git_commit 545c88d71d40a49ebdfb1d268c724110793330d2
gives stdout of:
local-gc-545c88d71d40a49ebdfb1d268c724110793330d2
(don't yet have uploading turned on in this branch)
=> snapshot/cli: cli to snapshot db

scootapi/client/get_status_cmd.go
Add option for more parseable format
=> scootapi/client - Flag for get status to output as json

scootapi/client/watch_job_cmd.go, snapshot/git/gitdb/bundlestore.go
=> gitdb: handle error better

binaries/apiserver/main.go, binaries/scheduler/config/config.go, binaries/scheduler/main.go, binaries/scoot-snapshot-db/main.go, binaries/scootapi/main.go, binaries/setup-cloud-scoot/main.go, binaries/workerserver/config/config.go, binaries/workerserver/main.go, common/endpoints/setup.go, config/jsonconfig/config.go, ice/eval.go, runner/execer/execer.go, runner/runners/chaos.go, runner/runners/invoke.go, runner/runners/polling.go, runner/runners/queue.go, runner/runners/status_manager.go, sched/scheduler/cluster_state.go, sched/scheduler/stateful_scheduler.go, sched/scheduler/task_runner.go, sched/scheduler/task_runner_test.go, scootapi/client/smoke_test_cmd.go, scootapi/server/setup.go, snapshot/git/gitdb/bundlestore.go, workerapi/server/server.go, workerapi/server/setup.go
[schedulerLog.txt](https://github.com/scootdev/scoot/files/856578/schedulerLog.txt)
the attached file contains the logging output from scheduler with this change (plus commented out log statement in fetcher.go in twitter source)
=> updated log statements

runner/runners/chaos.go, runner/runners/invoke.go, runner/runners/polling.go, runner/runners/queue.go, runner/runners/single_test.go
Also removed some spammy prints which aren't quite necessary anymore.
=> Added an info header to the top of our runner output.

scootapi/server/job_status.go
* Init JobStatus fields
* remove unrelated unnecessary if block
Not totally sure how to repro
=> scootapi/job_status - initialize TaskData and TaskStatus fields when job is not started

ice/eval.go, runner/runners/queue.go, runner/runners/status_manager.go, sched/scheduler/cluster_state.go
Also fixed ice's eval spew panic.
=> scheduler: Fixed panic in suspended node handling.

Makefile, runner/runners/queue.go, scootapi/client/run_job_cmd.go, snapshot/snapshots/setup.go, testCoverage.sh
Accidental commit to master. Reverts previous commit.
=> Revert 3300ea2e09ec8a55875aac4deed905376279e5b6

common/stats/stats_names.go, sched/scheduler/cluster_state.go, sched/scheduler/stateful_scheduler.go
Creating one location for  finding the list of stats being collected.  Let me know if you want me to merge this PR and create one more PR with the rest of the changes, or merge the rest of the changes into this PR.
=> Creating constants for the stats names. 

.gitmodules, deps.sh, runner/controller.go, runner/mocks/runner.go, runner/runners/chaos.go, runner/runners/queue.go, sched/scheduler/stateful_scheduler.go, snapshot/bundlestore/http_store.go, snapshot/bundlestore/server_test.go, workerapi/client/client.go
Should be a quick 'lgtm', as usual I'll add tests before landing.
=> bundlestore: added http retries. Also added Controller.Release().

snapshot/cli/cli.go
See code comment for explanation, and dx-2245
=> snapshot/cli - add refname to rev-list for publish git bundle

snapshot/git/gitdb/checkout.go, snapshot/git/gitdb/create.go, snapshot/git/gitdb/db_test.go, snapshot/git/repo/repo.go
* Refactor Run calls that use extra env vars
* Add db_test for cleanup fn
=> snapshot/repo - add cleanup function to repo Run cmds if process timed out

snapshot/git/repo/repo.go
Out of an abundance of caution - have observed git clean commands get timed out by the RunCmd wrapper
=> snapshot/repo - during cleanup due to git timeout, use context timeout on cleanup commands

snapshot/git/repo/repo.go
=> snapshot/repo - rm potential git lock after cleanup reset

sched/scheduler/task_runner.go, sched/scheduler/task_runner_test.go
DeadLetterExitCode was breaking the contract specified in runner/status.go
=> Removed DeadLetterExitCode in preference for an err msg.

common/log/helpers/helpers.go, workerapi/api.go, workerapi/server/server.go
=> workerapi/server: Log values instead of pointers
